# ZSHENV
# You can tell zsh to look for your
# configuration files in another folder by setting the parameter ZDOTDIR
# to a directory of your choice in your .zshenv file under $HOME:
# ZDOTDIR=/etc/my_kewl_folder/.zshrc
#
# Since .zshenv is always sourced, it often contains exported
# variables that #should be available to other programs. For
# example, $PATH, $EDITOR, # and #$PAGER are often set in .zshenv.
# Also, you can set $ZDOTDIR in .zshenv to #specify an alternative
# location for the rest of your zsh configuration.

EDITOR=vim
# PAGER
# ZDOTDIR

#references:
# https://github.com/robbyrussell/oh-my-zsh/pull/269
# source: http://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html
skip_global_compinit=1


export DOTFILES="${HOME}/.dotfiles"
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
cdpath=(. .. ~/Desktop ~/.dotfiles/bin ~/docs ~/docs/img ~/tmp ~/videos)

path=( $DOTFILES/bin $path[@])

# Path to your oh-my-zsh installation.
export ZSH="${DOTFILES}/oh-my-zsh"
export ZSH_CONFIG="${DOTFILES}/rcfiles/zsh"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# python environment
#export PYTHONSTARTUP=~/.dotfiles/rcfiles/python/pythonstartup
export PYTHONSTARTUP="${DOTFILES}/rcfiles/python/pythonstartup-new"
export PYTHON_HISTORY_FILE=~/.python_history

typeset -U path cdpath fpath manpath


