# source: http://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html
skip_global_compinit=1


export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
# export MANPATH="/usr/local/man:$MANPATH"
#
cdpath=(. .. ~/Desktop ~/bin ~/docs ~/docs/img ~/tmp)
typeset -U path cdpath fpath manpath
path=(~/bin $path[@])

#fpath=( ${HOME}/.dotfiles/rcfiles/zsh/functions "${fpath[@]}" )
