# ZSHENV
# You can tell zsh to look for your
# configuration files in another folder by setting the parameter ZDOTDIR
# to a directory of your choice in your .zshenv file under $HOME:
# ZDOTDIR=/etc/my_kewl_folder/.zshrc
#
# Since .zshenv is always sourced, it often contains exported
# variables that #should be available to other programs. For
# example, $PATH, $EDITOR, # and #$PAGER are often set in .zshenv.
# Also, you can set $ZDOTDIR in .zshenv to #specify an alternative
# location for the rest of your zsh configuration.

# avoid global loading environmente settings
unsetopt GLOBAL_RCS

EDITOR=vim

export TERM="xterm-256color"

# export XDG_DESKTOP_DIR="$HOME/Desktop"
# export XDG_DOWNLOAD_DIR="$HOME/downloads"
# export XDG_TEMPLATES_DIR="$HOME/docs/templates"
# export XDG_PUBLICSHARE_DIR="$HOME/docs/public"
# export XDG_DOCUMENTS_DIR="$HOME/docs"
# export XDG_MUSIC_DIR="$HOME/multimedia/music"
# export XDG_PICTURES_DIR="$HOME/multimedia/img"
# export XDG_VIDEOS_DIR="$HOME/multimedia/videos"


# PAGER

export LANG="pt_BR.UTF-8"
export LANGUAGE="pt_BR:pt:pt_PT"
export LC_ALL="pt_BR.UTF-8"

#export XDG_CONFIG_HOME="$HOME/.config"
#export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export DOTFILES="$HOME/.dotfiles"
export XDG_CACHE_HOME="$HOME/.cache"
export ZSH_CONFIG="$DOTFILES/rcfiles/zsh"

# Path to your oh-my-zsh installation.
export ZSH="${DOTFILES}/oh-my-zsh"

# python environment
#export PYTHONSTARTUP=~/.dotfiles/rcfiles/python/pythonstartup
export PYTHONSTARTUP="${DOTFILES}/rcfiles/python/pythonstartup-new"
export PYTHON_HISTORY_FILE=~/.python_history

ZSH_CACHE_DIR=${HOME}/.zsh.d/cache
# mkdir -p ${ZSH_CACHE_DIR}

#references:
# https://github.com/robbyrussell/oh-my-zsh/pull/269
# source: http://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html
skip_global_compinit=1

export PATH="/usr/local/sbin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
cdpath=(. .. ~/Desktop ~/.dotfiles/bin ~/.config/zsh ~/docs ~/docs/img ~/tmp ~/videos)

path=(${DOTFILES}/bin $path[@])
typeset -U path cdpath fpath manpath

