# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.dotfiles/oh-my-zsh"

[[ -d $HOME/.gem/ruby/2.3.0/bin ]] && PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin


#[ -d ~/bin ] && PATH=~/bin:$PATH &&  export PATH
[ -d /bin ] && PATH=/bin:$PATH &&  export PATH

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"


ZSH_CONFIG=~/.dotfiles/rcfiles/zsh

# sources:
# https://codegists.com/code/fasd/
# http://www.inmotionhosting.com/support/website/ssh/speed-up-grep-searches-with-lc-all
function add_locale() {
    if [[ -z "$($GREP __LC_CTYPE $RC)" ]]; then
        cat >>$RC <<HERE

        # __LC_CTYPE
        export LC_CTYPE=\$LANG
HERE
    fi
}


# 10ms for key sequences
KEYTIMEOUT=1

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="agnoster"
ZSH_THEME="bira"

setopt COMPLETE_ALIASES # complete aliases before executing
setopt NO_FLOW_CONTROL # deactvates XOFF
setopt COMPLETE_ALIASES
setopt INTERACTIVE_COMMENTS # allow inline comments like this one
# allow inline comments like this one
setopt HIST_VERIFY
setopt PROMPT_BANG # enables '!' substituition on prompt
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

setopt COMPLETE_IN_WORD     # Allow completion from within a word/phrase
setopt ALWAYS_TO_END
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=${HOME}/.dotfiles/rcfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git fasd extract systemd.plugin.zsh command-not-found history-substring-search )

plugins+=(zsh-autosuggestions zsh-autopair)

eval "$(fasd --init auto)"
eval "$(fasd --init posix-alias zsh-hook)"

# trying to expand gudo at the begining
bindkey '^i' expand-or-complete-prefix

bindkey '^Xw' expand-word # expande variáveis

for f in $HOME/.dotfiles/rcfiles/zsh/functions/*(.N); source $f

# testing completions
# https://github.com/zsh-users/zsh-completions
plugins+=(zsh-completions)
plugins+=(python)
export PYTHONDONTWRITEBYTECODE=1

autoload -U compinit && compinit

setopt complete_in_word

autoload -U zmv
alias mmv='noglob zmv -W'

# In Zsh ^W removes words delimited by whitespace. We are working in shell here though,
# this should be more fine-grained. I like how it behave in b#ash - slashes,
# dots and few other things are treated as delimiters too. You can achieve this behaviour in Zsh by simply:
autoload -U select-word-style
select-word-style bash


# User configuration
# export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd:cd ..:cd.."
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear:clr:[bf]g"
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY

export LANG="pt_BR.UTF-8"
export LANGUAGE="pt_BR:pt:pt_PT"
export LC_ALL="pt_BR.UTF-8"

source $ZSH/oh-my-zsh.sh

# If you end up using a directory as argument,
# this will remove the trailing slash (usefull in ln)
zstyle ':completion:*' squeeze-slashes true

# HISTORY
HISTSIZE=10000
SAVEHIST=9000
HISTFILE=~/.zsh_history

# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

# Fuzzy matching of completions for when you mistype them:
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# And if you want the number of errors allowed by _approximate to
# increase with the length of what you have typed so far:
zstyle -e ':completion:*:approximate:*' \
    max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'


zstyle ':completion:*:*:cd:*' ignored-patterns '(*/|)(CVS|SCCS)'
zstyle ':completion::*:(cvs-add|less|rm|vi):*' ignore-line true
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*:functions' ignored-patterns '_*'

# completions made case insensitive
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
#zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*'
#zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'm:{a-zA-Z}={A-Za-z}'

#zstyle ':completion:::::' completer _complete _prefix
#zstyle ':completion::prefix:::' completer _complete
zstyle ':completion::*:::' completer _complete _prefix


zstyle ':completion:*:warnings' format 'Too bad there is nothing'

ZSH_CACHE_DIR=${HOME}/.zsh.d/cache
mkdir -p ${ZSH_CACHE_DIR}


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
#if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='vim'
#else
#export EDITOR='mvim'
#fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

source ~/.dotfiles/rcfiles/zsh/aliases

current_wallpaper=$(gsettings get org.gnome.desktop.background picture-uri | sed 's,file:///,/,g' )

# emacs mode
bindkey -e

autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line
bindkey '^xe' edit-command-line

bindkey '^b' push-line-or-edit
bindkey '\eb' push-line-or-edit

# Grep anywhere with ^G
# don't try to type ^G instead use Ctrl-v Ctrl-g
bindkey -s '' ' | grep '

insert-history-line() {
LBUFFER="$LBUFFER\$(${history[$((HISTNO-1))]})"
}
zle -N insert-history-line insert-history-line
bindkey '^[e' insert-history-line

insert-history-line() {
LBUFFER="$LBUFFER\$(${history[$((HISTNO-1))]})"
}
zle -N insert-history-line insert-history-line
bindkey '^[e' insert-history-line

# allows me to bring vim back atter pressing ctrl-z
# by pressint it agaia
# source http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
fancy-ctrl-z () {
if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
else
    zle push-input
    zle clear-screen
fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# getting git status
function _git-status {
zle kill-whole-line
zle -U "git status"
zle accept-line
}
zle -N _git-status
bindkey '\eg' _git-status

# history search
# see: http://stackoverflow.com/questions/14040351/filtering-zsh-history-by-command
#function exists { which $1 &> /dev/null }

# if exists percol; then
#     function percol_select_history() {
#         local tac
#         exists gtac && tac="gtac" || { exists tac && tac="tac" || { tac="tail -r" } }
#         BUFFER=$(fc -l -n 1 | eval $tac | percol --query "$LBUFFER")
#         CURSOR=$#BUFFER         # move cursor
#         zle -R -c               # refresh
#     }
#
#     zle -N percol_select_history
#     bindkey '^R' percol_select_history
# fi

# # define widget function
# function cursor-after-first-word {
#     zle up-history
#     zle beginning-of-line
#     zle forward-word
#     RBUFFER=" $RBUFFER"
# }
# create widget from function
#zle -N cursor-after-first-word
# bind widget to ESC-o
#bindkey '^[o' cursor-after-first-word

# Inserts 'sudo ' at the beginning of the line.
function prepend-sudo {
  if [[ "$BUFFER" != su(do|)\ * ]]; then
    BUFFER="sudo $BUFFER"
    (( CURSOR += 5 ))
  fi
}
zle -N prepend-sudo
bindkey '^Xs' prepend-sudo

bindkey "^R" history-incremental-pattern-search-backward
bindkey "^S" history-incremental-pattern-search-forward

# source: http://goo.gl/HUXBjG
globalias() {
    if [[ $LBUFFER =~ ' [A-Z0-9]+$' ]]; then
        zle _expand_alias
        zle expand-word
    fi
    zle self-insert
}

zle -N globalias

bindkey ' ' globalias                # expande aliases globais
bindkey '^X ' magic-space            # control-space to bypass completion
#bindkey -M isearch " " magic-space  # normal space during searches
#bindkey -s '\eu' 'cd ..^j' # alt-u up dir

# source: http://stackoverflow.com/questions/171563/whats-in-your-zshrc
# I often build elaborate commands step by step: I run a command,
# see I need a different option, then use the output of the same
# command within # $() (the portable version of backquotes) in a
# for loop or something. The following snippet makes alt-E (I
# should probably write meta-E?) insert the previous line
# between $().

insert-history-line() {
    LBUFFER="$LBUFFER\$(${history[$((HISTNO-1))]})"
}
zle -N insert-history-line insert-history-line
bindkey '^[e' insert-history-line

# quote pasted URLs
# it seems kind of uncompatible with substring-search
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

# in order to install auto-suggestions plugin
# https://github.com/zsh-users/zsh-autosuggestions
# this key binding must be here at the end because of something I dont know yet
bindkey '^ ' autosuggest-accept
source ~/.dotfiles/rcfiles/zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey '^X^A' fasd-complete
bindkey '^X^F' fasd-complete-f
bindkey '^X^D' fasd-complete-d

# http://stackoverflow.com/a/13614816/2571881
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^h' history-beginning-search-menu

# firefox improviments
# disalbe rendering fonts in firefox to free memory
export MOZ_DISABLE_PANGO='1'
export OOO_FORCE_DESKTOP=gnome # For OpenOffice to look more gtk-friendly.

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden  --follow --glob "!.git/*"'

GNOME_VERSION=$(gnome-shell --version)

# python environment
#export PYTHONSTARTUP=~/.dotfiles/rcfiles/python/pythonstartup
export PYTHONSTARTUP=~/.dotfiles/rcfiles/python/pythonstartup-new
export PYTHON_HISTORY_FILE=~/.python_history
export LC_TIME=us_US.UTF-8
