#!/usr/bin/env zsh

askage() {
  trap '' SIGINT SIGTERM
  vared -p "How old are you? " -c age
  if [[ "$age" == "49" ]]; then
	   echo "You got it"
  else
       echo "Wron answer"
	   sleep 1
       exit 1
  fi
}
