#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# Author:       Sergio Araujo
# Last Change:  nov 03 2018 17:55
# Created:      qui 26 jan 2017 15:45:14 BRT
# email:        <voyeg3r ✉ gmail.com>
# Github:       https://github.com/voyeg3r
# twitter:      @voyeg3r

""" Esse script tem como proósito manipular strings
    removendo alguns caracteres para facilitar a criação
    de strings no programa Anki

    Caso não tenha a bibilioteca python-pyperclip instalada
    o comando no Arch-linux é este:

    yaourt -S python-pyperclip
    https://docs.python.org/3.6/library/unicodedata

    Here we make use of pyperclip library
    Python module for cross-platform clipboard functions

    https://pypi.python.org/pypi/pyperclip
    https://github.com/asweigart/pyperclip
"""

import unicodedata
import string
import pyperclip
import sys

argument = sys.argv[1:] if len(sys.argv) > 1 else sys.stdin.read()
argument = ''.join(argument).lower()

check = string.ascii_lowercase + ' '

output = unicodedata.normalize('NFKD', argument).encode('ascii', 'ignore')
output = output.decode('utf-8')
output = ''.join(ch for ch in output if ch in check)
output = output.replace(' ', '-')
output = output + '.mp3'

# print("Your string was copied to the clipboard:")
print(output)
pyperclip.copy(output)
