#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
#        File:  randplay
#      Author:  Sergio Araujo
#     Purpose:  Play a random song
# Last Change:  2018 mai 22 13:39
#     Created:  sex 11 mai 2018 09:53:01 -03
#       email:  <voyeg3r ✉ gmail.com>
#      Github:  https://github.com/voyeg3r
#     twitter:  @voyeg3r
#  Rererences:  https://stackoverflow.com/a/41911914/2571881
#               http://www.pythonforbeginners.com/error-handling/python-try-and-except/

import os
import random
import subprocess

def cls():
    if os.name == 'posix':
        os.system('clear')
    else:
        os.system('cls')

cls()

n = 0
random.seed()
for root, dirs, files in os.walk('/home/sergio/music/mpb'):
    for name in files:
        if name.endswith("mp3"):
            n+=1
            if random.uniform(0,n) < 1: rfile=os.path.join(root, name)

file = rfile

try:
    print(f'-'*80)
    print('Playing...')
    print(file)
    print(f'-'*80)
    subprocess.Popen(['mpg123', '-q', file]).wait()
except KeyboardInterrupt:
    cls()
    print('You cancelled the operation.')

