#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
#        File:  <+Filename Here+>
#      Author:  Sergio Araujo
#     Purpose:  <+this script aims...+>
# Last Change:  qua 16 mai 2018 09:59:37 -03
#     Created:  qua 16 mai 2018 09:59:37 -03
#       email:  <voyeg3r ✉ gmail.com>
#      Github:  https://github.com/voyeg3r
#     twitter:  @voyeg3r

# sudo pip install pyperclip

from subprocess import Popen
import webbrowser
import sys
import pyperclip
import pyautogui
import time

if len(sys.argv) > 1:
    address = ' '.join(sys.argv[1:])
else:
    address = pyperclip.paste()

address='https://www.google.com/maps/place/' + address

Popen(["firefox", address])

time.sleep(20)
pyautogui.click(100,200)
pyautogui.press('enter')
