#!/bin/sh
# File: /home/sergio/.dotfiles/bin/scratchy
# Last Change: Thu, 28 Apr 2022 13:44
# source: https://www.unixfandom.com/content/html/bspwm-scratchpad.html

id=$(xdotool search --class scratchy);
if [ -z "$id" ]; then
        st -c scratchy -n scratchy;
else
        if [ ! -f /tmp/hide_scratch ]; then
                touch /tmp/hide_scratch && xdo hide "$id"
        elif [ -f /tmp/hide_scratch ]; then
                rm /tmp/hide_scratch && xdo show "$id"
        fi
fi

