#!/usr/bin/env zsh
# functions
today(){date +%d-%m-%Y ;}
now(){ date +%H:%M;}
mktbz () { tar cvjf "${1%%/}.tar.bz2" "${1%%/}/";}
groove-dl-cli(){ python2.7 /usr/share/groove-dl/groove.py "$@" ;}
man2pdf () { man -w $1 && man -t $1 | ps2pdf - $1.pdf; }
yt () mplayer -fs -quiet $(youtube-dl -g "$1")
gsend() { git commit -am "$1" && git push ;}
lowerstring() { echo "${*}" | sed 's/./\L&/g' ;}
lower (){ echo ${@:l} }  # this versio only works in zsh
lcase (){ local var=$(pbpaste); print ${var:l} }
upper (){ echo ${@:u} }  # this versio only works in zsh
expandurl() { curl -sIL $1 | awk '/^Location/ || /^Localização/ {print $2}' ; }
calc(){ echo "scale=2;$@" | bc;}
ff () { find . -type f -iname '*'"$@"'*' ; }
mkcd() { mkdir -p "$@" && cd $_; }
decToBin () { echo "ibase=10; obase=2; $1" | bc; }
decTohex () { bc <<< "obase=16; $1"; }
biggest (){ du -k * | sort -nr | cut -f2 | head -20 | xargs -d "\n" du -sh; }
top10 () { history | awk '{print $2}' | sort | uniq -c | sort -rn | head ; }
beep () { echo -e -n \\a ; }
dict() { curl "dict://dict.org/d:${1%%/}";}
cmdfu(){ curl "http://www.commandlinefu.com/commands/matching/$@/$(echo -n $@ | openssl base64)/plaintext"; }

foreground-vi() {
fg %vi
}
zle -N foreground-vi
bindkey '^Z' foreground-vi

youtube-mp3 () {
# get mp3 from youtube
    command -v ffmpeg >/dev/null && youtube-dl --restrict-filenames --extract-audio --audio-format=mp3 --audio-quality 320k "${1}"
        [[ $? = 1 ]] && echo "instale o programa ffmpeg para poder converter para mp3"
}


# fzf settings ##############################################
# ZSH keybinding example; ~/.zshrc
fzf_history() { zle -I; eval $(history | fzf +s | sed 's/ *[0-9]* *//') ; }; zle -N fzf_history; bindkey '^h' fzf_history
fzf_killps() { zle -I; ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9} ; }; zle -N fzf_killps; bindkey '^Q' fzf_killps
fzf_cd() { zle -I; DIR=$(find ${1:-*} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf) && cd "$DIR" ; }; zle -N fzf_cd; bindkey '^x^d' fzf_cd

# vimf - Open selected file in Vim
vimf() {
    FILE=$(fzf) && vim "$FILE"
}

# fd - cd to selected directory
fd() {
    DIR=$(find ${1:-*} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf) && cd "$DIR"
}

# fda - including hidden directories
fda() {
    DIR=$(find ${1:-.} -type d 2> /dev/null | fzf) && cd "$DIR"
}

# fh - repeat history
fh() {
    eval $(history | fzf +s | sed 's/ *[0-9]* *//')
}

# fkill - kill process
fkill() {
    ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9}
}

# End fzf settings


dumpwnyc () {
    mplayer -playlist "http://www.wnyc.org/stream/wnyc-fm939/mp3.pls" -dumpstream -dumpfile wnyc-`date +%Y-%b-%d--%H.%Mhs`.mp3
}

record(){
# references:
# http://mocha.freeshell.org/audio.html
# http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
    [ -z "$1" ] && name="output.mp3" || name="$1"
        arecord -v -f cd -t raw | lame -r - $name
}


# source: http://stackoverflow.com/questions/35524958/push-local-git-repo-with-sub-repos-vim
make-github-submodule () {
    git config -f .gitmodules submodule.$1.path $1
        git config -f .gitmodules submodule.$1.url https://github.com/$2.git
}


background() {
    "$@" &
}


# ctrl-p for zsh (when fzf is setted whith
# yaourt -S fzf comment these lines
# # source: https://goo.gl/Tts3vW (reddit)
ctrlp() {
		</dev/tty vim -c CtrlP
}
zle -N ctrlp
bindkey "^f" ctrlp


# como quase nunca uso Ctrl-s linkey ele com o sudo
add_sudo (){
		prefix="sudo"
		BUFFER="$prefix $BUFFER"
		CURSOR=$(($CURSOR + $#prefix + 1))
}
zle -N add_sudo
bindkey "^s" add_sudo
