#!/usr/bin/env zsh
# functions
today(){date +%d-%m-%Y ;}
now(){ date +%H:%M;}
mktbz () { tar cvjf "${1%%/}.tar.bz2" "${1%%/}/";}
man2pdf () { man -w $1 && man -t $1 | ps2pdf - $1.pdf; }
yt () mplayer -fs -quiet $(youtube-dl -g "$1")
gsend() { git commit -am "$1" && git push ;}
lowerstring() { echo "${*}" | sed 's/./\L&/g' ;}
lower (){ echo ${@:l} }  # this versio only works in zsh
lcase (){ local var=$(pbpaste); print ${var:l} }
upper (){ echo ${@:u} }  # this versio only works in zsh
expandurl() { curl -sIL $1 | awk '/^Location/ || /^Localização/ {print $2}' ; }
calc(){ echo "scale=2;$@" | bc;}
ff () { find . -type f -iname '*'"$@"'*' ; }
mkcd() { mkdir -p "$@" && cd $_; }
decToBin () { echo "ibase=10; obase=2; $1" | bc; }
decTohex () { bc <<< "obase=16; $1"; }
biggest (){ du -k * | sort -nr | cut -f2 | head -20 | xargs -d "\n" du -sh; }
top10 () { history | awk '{print $2}' | sort | uniq -c | sort -rn | head ; }
beep () { echo -e -n \\a ; }
dict() { curl "dict://dict.org/d:${1%%/}";}
cmdfu(){ curl "http://www.commandlinefu.com/commands/matching/$@/$(echo -n $@ | openssl base64)/plaintext"; }

foreground-vi() {
fg %vi
}
zle -N foreground-vi
bindkey '^Z' foreground-vi

youtube-mp3 () {
# get mp3 from youtube
    command -v ffmpeg >/dev/null && youtube-dl --restrict-filenames --extract-audio --audio-format=mp3 --audio-quality 320k "${1}"
        [[ $? = 1 ]] && echo "instale o programa ffmpeg para poder converter para mp3"
}


dumpwnyc () {
    # source: https://shkspr.mobi/blog/2011/11/watching-and-simultaneously-saving-video-in-mplayer/
    # mplayer "$url" -dumpstream -dumpfile wnyc-`date +%Y-%b-%d--%H.%Mhs`.mp3

    station="wnyc"
    url="http://fm939.wnyc.org/wnycfm-tunein.aac"
    filename=${station}-$(date +%Y-%b-%d--%H.%Mhs).mp3
    wget -O - "$url" | tee -ai "$filename" | mpg123 -
}

dumpscifi () {
    # source: https://shkspr.mobi/blog/2011/11/watching-and-simultaneously-saving-video-in-mplayer/
    # mplayer "$url" -dumpstream -dumpfile scifi-`date +%Y-%b-%d--%H.%Mhs`.mp3

    station="scifi-old"
    url="http://198.178.123.2:8652/;stream/1"
    filename=${station}-$(date +%Y-%b-%d--%H.%Mhs).mp3
    wget -O - "$url" | tee -ai "$filename" | mpg123 -
}

dumpamazingtale (){
    station="amazing-tale"
    url="http://rosetta.shoutca.st:8462/;stream1"
    filename=${station}-$(date +%Y-%b-%d--%H.%Mhs).mp3
    wget -O - "$url" | tee -ai "$filename" | mpg123 -
}

record(){
# references:
# http://mocha.freeshell.org/audio.html
# http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
    [ -z "$1" ] && name="output.mp3" || name="$1"
        arecord -v -f cd -t raw | lame -r - $name
}


# source: http://stackoverflow.com/questions/35524958/push-local-git-repo-with-sub-repos-vim
make-github-submodule () {
    git config -f .gitmodules submodule.$1.path $1
        git config -f .gitmodules submodule.$1.url https://github.com/$2.git
}


background() {
    "$@" &
}

# como quase nunca uso Ctrl-s linkey ele com o sudo
add_sudo (){
		prefix="sudo"
		BUFFER="$prefix $BUFFER"
		CURSOR=$(($CURSOR + $#prefix + 1))
}
zle -N add_sudo
bindkey "^s" add_sudo
