#!/bin/bash
# Filename: rofi-files
# Last Change: Wed, 14 Sep 2022 15:24:11
# source: https://github.com/GabrielTWMlinux/Scripts/blob/main/Rofi/rofi-files
# vim: tabstop=4 shiftwidth=4 softtabstop=4 expandtab ft=sh:

export DMEDITOR="nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
"awesome - $HOME/.config/awesome/rc.lua"
"zsh - $HOME/.config/zsh/.zshrc"
"neovim - $HOME/.config/nvim/init.lua"
"picom - $HOME/.config/picom/picom.conf"
"gtk-css - $HOME/.config/gtk-3.0/gtk.css"
"files - $HOME/dwm/scripts/searchfiles"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i  20 -p ' Editar ')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi
